### ISSUE TITLE
Add an extensive error message for incorrect repositories

### ISSUE THREAD

**Issue by jaapromijn** [RonRademaker/ReleaseBuilder#18]
In the command, when you enter an incorrect repository option, the release builder throws the error:

> Error updating FILENAME: Not Found

It would be easier to find your error when the release builder checks the repository and throws an error  when the repository is not found.

**Comment by RonRademaker** [comment]
Thanks, will add a better error message in the upcoming release (or if you want to create a PR for this, you're of course welcome to create one).

**Comment by RonRademaker** [comment]
The improved error message (```Unable to set version in src/Command/ReleaseCommand.php in RonRademaker/ReleasedfdsafdsBuilder because that file does not exist in that repository``` instead of ```Error updating src/Command/ReleaseCommand.php: Not Found```) is available in the latest release (0.8.1). 

I closed the issue, feel free to reopen if this doesn't completely fix your issue.
